/* ============================================================================
   Las frases de la casa, en inglés — compartidas por el portal del cliente
   (cliente.html) y la portada del contratista (gc.html).
   Los hitos se escriben en español en la ficha; al cliente que lee en inglés
   se le traducen por frase, no palabra por palabra. Si una frase no está en
   esta lista, sale tal cual: nunca se inventa una traducción.
   ============================================================================ */
window.MXP_FRASES = [
  /* Las 20 que todavía salían en español — 24-sep (P36) */
  [/^Al completar el pathway y las 4 corridas de Cat6 · firmado por el cliente el (\d+)-ago$/i, "On completion of the pathway and the 4 Cat6 runs · signed by the client on Aug $1"],
  [/^Al completar el trabajo$/i, "On completion of the work"],
  [/^Al firmar \/ movilización \(cobrado en un año fiscal anterior\)$/i, "On signing / mobilization (collected in a prior fiscal year)"],
  [/^Al firmar el contrato$/i, "On signing the contract"],
  [/^Al terminar el rough-in \(no depende del drywall ni de los fixtures del dueño\)$/i, "On completion of the rough-in (does not depend on drywall or the owner's fixtures)"],
  [/^Change Order #(\d+) — Cat6 data pathway \(50% depósito, cobrado con M2\)$/i, "Change Order #$1 — Cat6 data pathway (50% deposit, collected with M2)"],
  [/^Change Order #(\d+) — cocina\/comedor Rev\. (\d+) \+ baño master$/i, "Change Order #$1 — kitchen/dining Rev. $2 + master bath"],
  [/^Change order \(requerido por el inspector\) cobrado (\S+)$/i, "Change order (required by the inspector) collected $1"],
  [/^Devices finales, programación del sistema e inspección final aprobada$/i, "Final devices, system programming and final inspection passed"],
  [/^Facturado aparte el (\d+)-sep \((\S+)\)$/i, "Invoiced separately on Sep $1 ($2)"],
  [/^Fee de supervisión y revisión para el permiso$/i, "Supervision and review fee for the permit"],
  [/^Inspección final pasada$/i, "Final inspection passed"],
  [/^Pago completo al terminar \(sin depósito, por el monto del contrato\)$/i, "Full payment on completion (no deposit, for the contract amount)"],
  [/^Pago único al completar$/i, "Single payment on completion"],
  [/^Pago único — al completar el trabajo$/i, "Single payment — on completion of the work"],
  [/^Rough-in terminado \(canalización, cajas y circuitos\)$/i, "Rough-in complete (raceways, boxes and circuits)"],
  [/^Sin depósito: el total a los (\d+) días de terminar$/i, "No deposit: the full amount $1 days after completion"],
  [/^Trabajo ya hecho por otros; revisión en sitio y trámite del permiso$/i, "Work already done by others; on-site review and permit processing"],
  [/^Trim terminado$/i, "Trim complete"],
  [/^Trim, fixtures e inspección final aprobada$/i, "Trim, fixtures and final inspection passed"],
  [/^Añadido — .*$/i, "Add-on work"],
  [/Milestone (\d+) — (\d+)% movilización/i, "Milestone $1 — $2% mobilization"],
  [/Milestone (\d+) — (\d+)% avance/i, "Milestone $1 — $2% progress"],
  [/Milestone (\d+) — (\d+)% final/i, "Milestone $1 — $2% final"],
  [/Milestone (\d+) — (\d+)% depósito/i, "Milestone $1 — $2% deposit"],
  [/Milestone (\d+) — (\d+)% rough y trim/i, "Milestone $1 — $2% rough and trim"],
  [/Milestone (\d+) — (\d+)% servicio y rough/i, "Milestone $1 — $2% service and rough"],
  [/^Milestone (\d+) — base \((\d+)%\)$/i, "Milestone $1 — base contract ($2%)"],
  [/^Milestone (\d+) — base, Fase (\d+) pre-stucco$/i, "Milestone $1 — base contract, Phase $2 pre-stucco"],
  [/^Depósito (\d+)%$/i, "Deposit $1%"],
  [/^(\d+)% final$/i, "$1% final"],
  [/^(\d+)% al completar$/i, "$1% on completion"],
  [/^Saldo del alcance base$/i, "Balance of the base scope"],
  [/^Adicional directo — (\d+)% final$/i, "Additional work — final $1%"],
  [/^Adicional directo — (\d+)%$/i, "Additional work — $1%"],
  [/^Generador — depósito (\d+)%$/i, "Generator — $1% deposit"],
  [/^Generador — (\d+)% instalación completa$/i, "Generator — $1%, installation complete"],
  [/^Generador — (\d+)% final$/i, "Generator — final $1%"],
  [/^Change Order (\S+) — depósito (\d+)%$/i, "Change Order $1 — $2% deposit"],
  [/^Change Order (\S+) — (\d+)% final$/i, "Change Order $1 — final $2%"],
  [/^Al pasar (la )?inspección final$/i, "On passing the final inspection"],
  [/^Al pasar la inspección de rough$/i, "On passing the rough inspection"],
  [/^Al aceptar( la propuesta)?.*$/i, "On acceptance of the proposal"],
  [/^Al firmar y movilizar$/i, "On signing and mobilization"],
  [/^Al completar (el trabajo añadido|la obra)$/i, "On completion of the work"],
  [/^Al completar el alcance base$/i, "On completion of the base scope"],
  [/^Al completar el adicional$/i, "On completion of the additional work"],
  [/^Al terminar el trabajo.*$/i, "On completion of the work"],
  [/^Al terminar el Change Order$/i, "On completion of the Change Order"],
  [/^Al terminar el Change Order \(incluye material al costo y descuento\)$/i,
   "On completion of the Change Order (includes materials at cost and the discount)"],
  [/^Rough \/ avance principal completo$/i, "Rough-in / main progress complete"],
  [/^Rough y trim completos$/i, "Rough-in and trim complete"],
  [/^Movilización$/i, "Mobilization"],
  [/^Fase (\d+) completa$/i, "Phase $1 complete"],
  [/^Avance del adicional$/i, "Progress on the additional work"],
  [/^Equipo montado, cableado y conectado \(Sección (\d+) del SOW\)$/i, "Equipment set, wired and connected (Section $1 of the SOW)"],
  [/^Inspección final aprobada y el sistema funcionando$/i, "Final inspection passed and the system running"],
  [/^Pagado con la factura (\S+)$/i, "Paid with invoice $1"],
  [/^Cobrado el (\d+)-ene$/i, "Paid Jan $1"], [/^Cobrado el (\d+)-feb$/i, "Paid Feb $1"],
  [/^Cobrado el (\d+)-mar$/i, "Paid Mar $1"], [/^Cobrado el (\d+)-abr$/i, "Paid Apr $1"],
  [/^Cobrado el (\d+)-may$/i, "Paid May $1"], [/^Cobrado el (\d+)-jun$/i, "Paid Jun $1"],
  [/^Cobrado el (\d+)-jul$/i, "Paid Jul $1"], [/^Cobrado el (\d+)-ago$/i, "Paid Aug $1"],
  [/^Cobrado el (\d+)-sep$/i, "Paid Sep $1"], [/^Cobrado el (\d+)-oct$/i, "Paid Oct $1"],
  [/^Cobrado el (\d+)-nov$/i, "Paid Nov $1"], [/^Cobrado el (\d+)-dic$/i, "Paid Dec $1"],
  /* Los hitos «Milestone N de M» y las condiciones cortas que usa Edgar
     (repasadas contra los 60 hitos que hay hoy en la base) */
  [/^Milestone (\d+) de (\d+) — (\d+)% depósito$/i, "Milestone $1 of $2 — $3% deposit"],
  [/^Milestone (\d+) de (\d+) — (\d+)% final$/i, "Milestone $1 of $2 — final $3%"],
  [/^Milestone (\d+) de (\d+) — (\d+)%$/i, "Milestone $1 of $2 — $3%"],
  [/^Milestone (\d+) — (\d+)% depósito$/i, "Milestone $1 — $2% deposit"],
  [/^Milestone (\d+) — (\d+)% trim$/i, "Milestone $1 — $2% trim"],
  /* Los pagos que decide la IA (24-sep, P26) */
  [/^Milestone (\d+) — (\d+)% final$/i, "Milestone $1 — final $2%"],
  [/^Trim-out terminado \(equipos y terminaciones\)$/i, "Trim-out complete (devices and finishes)"],
  [/^Milestone (\d+) — (\d+)% rough$/i, "Milestone $1 — $2% rough-in"],
  [/^Milestone (\d+) — (\d+)%$/i, "Milestone $1 — $2%"],
  [/^CO #(\d+) — depósito (\d+)%$/i, "CO #$1 — $2% deposit"],
  [/^CO #(\d+) — (\d+)% final$/i, "CO #$1 — final $2%"],
  [/^Depósito (\d+)% \+ permiso al costo$/i, "Deposit $1% + permit at cost"],
  [/^Pago único — todo incluido$/i, "Single payment — all inclusive"],
  [/^Al aceptar el change order$/i, "On acceptance of the change order"],
  [/^Al aceptar la Fase (\d+)$/i, "On acceptance of Phase $1"],
  [/^Al completar$/i, "On completion"],
  [/^Al completar la instalación$/i, "On completion of the installation"],
  [/^Al completar y pasar inspección$/i, "On completion and passing inspection"],
  [/^Al terminar el CO #(\d+)$/i, "On completion of CO #$1"],
  [/^Según avance de la obra$/i, "As the work progresses"],
  [/^Al arrancar \(movilización\)$/i, "At start-up (mobilization)"],
  [/^Al firmar \/ movilizar$/i, "On signing / mobilization"],
  [/^Al pasar (el )?rough$/i, "On passing the rough inspection"],
  [/^Al pasar inspección final$/i, "On passing the final inspection"],
  [/^Al pasar inspección de rough$/i, "On passing the rough inspection"],
  [/^Al pasar power-release$/i, "On power release"],
  [/^Panel\/servicio reemplazado \+ rough completo$/i, "Panel/service replaced + rough-in complete"],
  /* Heather / Borders — 21-sep */
  [/^Evaluaci[oó]n, servicio del panel y circuito del shed$/i, "Evaluation, panel service and shed circuit"],
  [/^Subpanel del garaje \(Alcance C\)$/i, "Garage sub-panel (Scope C)"],
  [/^Trabajo terminado y facturado$/i, "Work completed and invoiced"],
  [/^Trabajo terminado y probado$/i, "Work completed and tested"]
];

/* ============================================================================
   Los textos nuevos del portal del cliente («Cobre y luz», tanda 3, 26-sep).
   cliente.html los junta con los suyos según el idioma elegido (inglés por
   defecto; el botón ES los cambia). {n}, {d}, {x} y {e} se rellenan allí.
   ============================================================================ */
window.MXP_PORTAL_TXT = {
  en: {
    aaEtiqueta: "Larger text",
    tuObra: "Your project", etapaDe: "{e} stage", servicio: "Service call", propuestaEtapa: "Proposal",
    enPausa: "On hold", enCurso: "In progress", terminada: "Completed", dondeT: "Where we are",
    etapas: ["Permit", "Rough-in", "Inspection", "Trim", "Final"],
    etapasT: "Job stages", etapaActual: "Current stage: ", todasListas: "All stages complete",
    trabajosT: "Work items", hechosCuenta: "{d} / {n} done", panelAria: "{d} of {n} items done",
    notaPanel: "Each breaker is one item of your scope.", verTodos: "Show all {n}", verMenos: "Show fewer",
    ahora: "Now", grupoCuenta: "{d} of {n} done", soloInfo: "For your information", irAlPunto: "Go to item {n}: ",
    visitaT: "Latest visit", verFotos: "See all photos ({n})", ocultarFotos: "Hide older photos",
    cerrar: "Close", fotoAlt: "Job photo", videoAlt: "Job video", abrirFoto: "Open photo",
    inspT: "Permit & inspections", paso: "Passed", fallo: "Needs corrections", programada: "Scheduled",
    permisoAria: "Permit number", jurisAria: "Jurisdiction",
    debeT: "Amount due", debeYa: "Due now", emitida: "issued {x}", verFactura: "View invoice",
    notaPago: "Pay by check or ACH. Card payments are available on request.",
    firmaT: "Needs your signature", aprobT: "Needs your approval",
    revisarFirmar: "Review and sign", revisarAprobar: "Review and approve", valeHasta: "Valid until {x}",
    pagadoT: "Paid to date", deContrato: "of {x} contract", proxT: "Next visit",
    pagosT: "Payment schedule", hitosN: "{n} milestones", hito1: "1 milestone",
    contratoT: "Contract total", facturadoT: "Invoiced", porFacturarT: "Not yet invoiced", saldoT: "Balance",
    hPagado: "Paid", hFacturado: "Invoiced", hProximo: "Upcoming", facturasT: "Invoices",
    fPagada: "Paid", fParcial: "Partly paid", fAbierta: "Open", fDetalleParcial: "Paid {x} · Balance {d}",
    decT: "Decisions we need from you", necesita: "We need it by {x}", decidi: "I've decided", hecha: "Done",
    diarioT: "Job log", verMas: "Show more", verMenosLog: "Show less",
    docsT: "Documents", stFirmado: "Signed", stAprobado: "Approved", stPideFirma: "Needs signature",
    stPideAprob: "Needs approval", stVencido: "Expired", stNoElegida: "Not selected",
    firmadoPor: "Signed by {x} on {d}", yOtro: " and ", ambos: "Signed by both parties",
    aprobadoEl: "Approved on {x}", codigoVer: "Verification code",
    edgarRol: "Licensed Electrical Contractor", licT: "License & insurance",
    llamar: "Call", mensaje: "Text", sitio: "mxpes.com",
    garantiaT: "Your warranty", cubierta: "Covered until {x}", resena: "Leave us a Google review",
    aprobarTit: "Approve this document", aprobarNota: "Open it and read it first. When it looks right, tap Approve.",
    aprobarBtn: "Approve", abrirDoc: "Open the document", abiertoOk: "Opened. You can sign now.",
    gcTodas: "All projects", gcPara: "For {x}"
  },
  es: {
    aaEtiqueta: "Letra más grande",
    tuObra: "Tu proyecto", etapaDe: "Etapa {e}", servicio: "Visita de servicio", propuestaEtapa: "Propuesta",
    enPausa: "En pausa", enCurso: "En curso", terminada: "Terminado", dondeT: "Dónde vamos",
    etapas: ["Permit", "Rough-in", "Inspection", "Trim", "Final"],
    etapasT: "Etapas de la obra", etapaActual: "Etapa actual: ", todasListas: "Todas las etapas terminadas",
    trabajosT: "Trabajos", hechosCuenta: "{d} / {n} hechos", panelAria: "{d} de {n} puntos hechos",
    notaPanel: "Cada breaker es un punto de tu alcance.", verTodos: "Ver los {n}", verMenos: "Ver menos",
    ahora: "Ahora", grupoCuenta: "{d} de {n} hechos", soloInfo: "Para que lo sepas", irAlPunto: "Ir al punto {n}: ",
    visitaT: "Última visita", verFotos: "Ver todas las fotos ({n})", ocultarFotos: "Ocultar las fotos viejas",
    cerrar: "Cerrar", fotoAlt: "Foto de la obra", videoAlt: "Video de la obra", abrirFoto: "Abrir la foto",
    inspT: "Permiso e inspecciones", paso: "Pasó", fallo: "Necesita correcciones", programada: "Programada",
    permisoAria: "Número de permiso", jurisAria: "Jurisdicción",
    debeT: "Por pagar", debeYa: "Vence ya", emitida: "emitida el {x}", verFactura: "Ver la factura",
    notaPago: "Pago con cheque o ACH. Con tarjeta, pídelo.",
    firmaT: "Necesita tu firma", aprobT: "Necesita tu aprobación",
    revisarFirmar: "Revisar y firmar", revisarAprobar: "Revisar y aprobar", valeHasta: "Vale hasta el {x}",
    pagadoT: "Pagado a la fecha", deContrato: "de un contrato de {x}", proxT: "Próxima visita",
    pagosT: "Calendario de pagos", hitosN: "{n} hitos", hito1: "1 hito",
    contratoT: "Contrato total", facturadoT: "Facturado", porFacturarT: "Sin facturar", saldoT: "Saldo",
    hPagado: "Pagado", hFacturado: "Facturado", hProximo: "Próximo", facturasT: "Facturas",
    fPagada: "Pagada", fParcial: "Pago parcial", fAbierta: "Abierta", fDetalleParcial: "Pagado {x} · Saldo {d}",
    decT: "Decisiones que necesitamos de ti", necesita: "La necesitamos antes del {x}", decidi: "Ya decidí", hecha: "Hecha",
    diarioT: "Diario de la obra", verMas: "Ver más", verMenosLog: "Ver menos",
    docsT: "Documentos", stFirmado: "Firmado", stAprobado: "Aprobado", stPideFirma: "Falta tu firma",
    stPideAprob: "Falta tu aprobación", stVencido: "Vencido", stNoElegida: "No elegida",
    firmadoPor: "Firmado por {x} el {d}", yOtro: " y ", ambos: "Firmado por las dos partes",
    aprobadoEl: "Aprobado el {x}", codigoVer: "Código de verificación",
    edgarRol: "Contratista eléctrico con licencia", licT: "Licencia y seguros",
    llamar: "Llamar", mensaje: "Mensaje", sitio: "mxpes.com",
    garantiaT: "Tu garantía", cubierta: "Cubierta hasta el {x}", resena: "Déjanos tu reseña en Google",
    aprobarTit: "Aprobar este documento", aprobarNota: "Ábrelo y léelo primero. Si está bien, toca Aprobar.",
    aprobarBtn: "Aprobar", abrirDoc: "Abrir el documento", abiertoOk: "Abierto. Ya puedes firmar.",
    gcTodas: "Todas las obras", gcPara: "Para {x}"
  }
};
