-- =====================================================================
-- 01-replica-esquema.sql — réplica de las tablas de producción que tocan
-- los libros. SOLO PARA EL BANCO DE PRUEBAS LOCAL.
--
-- Las columnas (nombre, tipo, default, not null) salen TAL CUAL de
-- information_schema.columns de producción, leído el 23-sep-2026
-- (esquema-columnas-23sep.json), con generar-tablas.py: no se escribieron
-- a mano.
-- Lo que information_schema NO dice y aquí es SUPUESTO:
--   * llaves primarias: "id" en todas; en las demás, la columna natural
--     (perfiles.id, proyectos.id, costos_equipo.usuario_id,
--     finanzas_proyecto.proyecto_id, codigos_partida.codigo,
--     contratistas.id, asistente_ajustes.clave, escenarios.id).
--   * las "id int8" sin default son "generated by default as identity"
--     (así nacen las tablas del dashboard de Supabase).
--   * NO hay llaves foráneas ni unique extra: no se leyeron. Ninguna prueba
--     debe depender de que un FK de producción exista o no exista.
-- Se carga como editor_sql, así que todo nace con los grants de Supabase.
-- =====================================================================

create table if not exists public.perfiles (
  id uuid primary key,
  nombre text not null,
  rol text not null,
  creado timestamptz default now(),
  activo boolean default true,
  en_grupo boolean default true,
  ultima_vista timestamptz
);

create table if not exists public.proyectos (
  id text primary key,
  tipo text not null,
  nombre text not null,
  direccion text,
  cliente text,
  via text,
  estado text not null,
  fase text,
  estado_detalle text,
  proxima_accion text,
  ref text,
  horas_estimadas numeric default 0,
  actualizado timestamptz default now(),
  horas_reales_base numeric default 0,
  portal_dinero boolean default false,
  portal_completo boolean default false,
  work_subtype text,
  estimado_ref text,
  qb_customer_id text,
  origen text,
  cliente_email text,
  cliente_tel text,
  puede_cancelar_hasta date,
  cierre_directo boolean,
  portal_invitado_el timestamptz,
  contratista_id text,
  contratista_modo text,
  nto_enviado_el timestamptz,
  nto_nota text,
  contratista_contacto text,
  portal_resumen text,
  portal_resumen_en text
);

create table if not exists public.facturas (
  id bigint generated by default as identity primary key,
  proyecto_id text,
  num text not null,
  fecha date,
  monto numeric,
  pagada boolean default false,
  hito_id bigint,
  qb_id text,
  link_pago text,
  cobrada_el timestamptz,
  metodo_cobro text,
  cobrado numeric(12,2),
  a_contratista boolean
);

create table if not exists public.recibos (
  id bigint generated by default as identity primary key,
  proyecto_id text,
  ruta text,
  total numeric,
  proveedor text,
  notas text,
  estado text default 'por_leer'::text,
  autor_id uuid,
  creado timestamptz default now(),
  co text,
  fecha date,
  categoria text default 'material'::text,
  subtotal numeric,
  tax numeric,
  num_recibo text,
  metodo_pago text,
  ultimos4 text,
  po_job text
);

create table if not exists public.horas (
  id bigint generated by default as identity primary key,
  fecha date not null,
  usuario_id uuid not null,
  proyecto_id text,
  fase text,
  horas numeric not null,
  notas text,
  creado timestamptz default now(),
  correccion_estado text,
  co text,
  llave_cliente text
);

create table if not exists public.materiales (
  id bigint generated by default as identity primary key,
  proyecto_id text,
  descripcion text not null,
  cantidad text,
  estado text default 'falta'::text,
  origen_pendiente bigint,
  autor_id uuid,
  creado timestamptz default now(),
  precio numeric,
  recibo_id bigint
);

create table if not exists public.trabajos_externos (
  id bigint generated by default as identity primary key,
  proyecto_id text,
  descripcion text not null,
  fecha date,
  tipo text default 'ajuste'::text,
  horas numeric,
  costo numeric not null,
  creado timestamptz default now(),
  externo_id bigint
);

create table if not exists public.externos_equipo (
  id bigint generated by default as identity primary key,
  nombre text not null,
  costo_hora numeric default 0 not null,
  activo boolean default true
);

create table if not exists public.costos_equipo (
  usuario_id uuid primary key,
  costo_hora numeric not null,
  actualizado timestamptz default now()
);

create table if not exists public.hitos (
  id bigint generated by default as identity primary key,
  proyecto_id text,
  titulo text not null,
  condicion text,
  monto numeric,
  estado text,
  orden integer default 0,
  es_deposito boolean default false not null
);

create table if not exists public.finanzas_proyecto (
  proyecto_id text primary key,
  contrato numeric,
  cobrado numeric default 0,
  presupuesto_materiales numeric
);

create table if not exists public.alcances (
  id bigint generated by default as identity primary key,
  proyecto_id text,
  tipo text,
  titulo text not null,
  ref text,
  monto numeric,
  cobrado numeric,
  estado text,
  orden integer default 0
);

create table if not exists public.codigos_partida (
  codigo text primary key,
  nombre text not null,
  nombre_en text not null,
  categoria text not null
);

create table if not exists public.contratistas (
  id text primary key,
  nombre text not null,
  contacto text,
  email text,
  telefono text,
  ve_dinero boolean default true not null,
  avisos boolean default true not null,
  activo boolean default true not null,
  notas text,
  invitado_el timestamptz,
  visto_el timestamptz,
  creado timestamptz default now() not null
);

create table if not exists public.asistente_uso (
  id bigint generated by default as identity primary key,
  usuario_id uuid,
  rol text,
  modelo text,
  entrada integer default 0,
  salida integer default 0,
  vueltas integer default 1,
  creado timestamptz default now(),
  accion text,
  cache_lectura integer default 0,
  cache_escritura integer default 0,
  ms integer,
  resultado text,
  costo_centavos integer,
  letras integer,
  proyecto_id text
);

create table if not exists public.asistente_ajustes (
  clave text primary key,
  valor text
);

create table if not exists public.escenarios (
  id text primary key,
  nombre text,
  foreman numeric,
  journeyman numeric,
  helper numeric,
  pct_foreman numeric,
  pct_journeyman numeric,
  pct_helper numeric,
  benefits numeric,
  tax_material numeric,
  overhead_hh numeric,
  profit numeric,
  mezcla jsonb,
  overhead_pct numeric,
  benefits_detalle jsonb
);

create table if not exists public.estimados (
  id bigint generated by default as identity primary key,
  nombre text not null,
  cliente text,
  direccion text,
  tipo text default 'Residential'::text,
  sqft numeric,
  factor numeric default 1,
  escenario text default 'B'::text,
  estado text default 'borrador'::text,
  creado timestamptz default now(),
  modo text default 'planos'::text,
  cable text default 'romex'::text,
  misc_pct numeric,
  tax_pct numeric,
  overhead_hh numeric,
  profit_pct numeric,
  markup_pct numeric,
  horas_directas numeric,
  lineas_material jsonb,
  benefits_pct numeric,
  mezcla jsonb,
  proyecto_id text,
  via text,
  contratista_id text,
  contratista_modo text,
  cliente_email text,
  cliente_tel text,
  contratista_contacto text,
  cero_notas jsonb default '{}'::jsonb not null,
  no_incluye_extra text,
  empresa text,
  markup_cot_pct numeric,
  overhead_pct numeric,
  meses_obra integer,
  escalacion_pct numeric,
  resultado text,
  resultado_fecha date,
  resultado_motivo text,
  resultado_nota text,
  competencia numeric,
  bid_final numeric,
  horas_final numeric,
  material_final numeric,
  cerrado_en timestamptz,
  notas text,
  soporte text,
  pct_rack numeric,
  usa_luz_ref boolean default false,
  valida_dias integer,
  dueno text,
  retencion_pct numeric,
  adjuntos jsonb
);

create table if not exists public.catalogo_items (
  id bigint generated by default as identity primary key,
  seccion text,
  item text not null,
  unidad text,
  precio numeric default 0,
  horas_unidad numeric default 0,
  orden integer default 0,
  codigo text,
  cero_motivo text,
  cero_revisado date,
  cero_nota text,
  precio_ref numeric,
  horas_ref numeric,
  fuente_ref text,
  ref_fecha date,
  precio_fecha date,
  precio_fuente text
);

create table if not exists public.pendientes (
  id bigint generated by default as identity primary key,
  fecha date not null,
  proyecto_id text,
  descripcion text not null,
  autor_id uuid,
  resuelto boolean default false,
  resuelto_por uuid,
  resuelto_el timestamptz,
  creado timestamptz default now(),
  prioridad text default 'normal'::text
);

create table if not exists public.gastos_generales (
  id bigint generated by default as identity primary key,
  concepto text not null,
  monto_mensual numeric not null
);


-- =====================================================================
-- Funciones de permiso: copiadas verbatim de producción. Se reutilizan
-- en todo el libro; no se inventa otro candado.
-- =====================================================================
create or replace function public.es_dueno() returns boolean
language sql stable security definer set search_path to 'public','pg_temp' as $$
  select exists (select 1 from perfiles
    where id = auth.uid() and rol = 'dueno' and coalesce(activo, true));
$$;

create or replace function public.es_activo() returns boolean
language sql stable security definer set search_path to 'public','pg_temp' as $$
  select coalesce((select coalesce(activo, true) from perfiles where id = auth.uid()), false);
$$;

-- =====================================================================
-- Triggers que ya existen en producción
-- =====================================================================

-- facturas: BEFORE INSERT OR UPDATE → trg_factura_cobrada (verbatim; en
-- producción NO tiene search_path fijo y aquí tampoco).
create or replace function public.fn_factura_cobrada() returns trigger language plpgsql as $$
begin
  if new.pagada = true and (old.pagada is distinct from true) and coalesce(new.cobrado, 0) < new.monto then
    new.cobrado := new.monto;
  end if;
  if new.cobrado is null then new.cobrado := case when new.pagada then new.monto else 0 end; end if;
  return new;
end $$;

drop trigger if exists trg_factura_cobrada on public.facturas;
create trigger trg_factura_cobrada before insert or update on public.facturas
  for each row execute function public.fn_factura_cobrada();

-- recibos: AFTER INSERT OR UPDATE → trg_recibo_marca_material (verbatim).
create or replace function public.fn_recibo_marca_material() returns trigger
language plpgsql security definer set search_path to 'public','pg_temp' as $$
begin
  if new.proyecto_id is not null and new.notas is not null
     and coalesce(new.estado, '') <> 'anulado' then
    update materiales m
      set estado = 'comprado', recibo_id = new.id
      where m.proyecto_id = new.proyecto_id
        and m.estado = 'falta'
        and length(trim(m.descripcion)) >= 6
        and strpos(lower(new.notas), lower(trim(m.descripcion))) > 0;
  end if;
  if tg_op = 'UPDATE' and new.estado = 'anulado' and coalesce(old.estado, '') <> 'anulado' then
    update materiales set estado = 'falta', recibo_id = null where recibo_id = new.id;
  end if;
  return new;
end $$;

drop trigger if exists trg_recibo_marca_material on public.recibos;
create trigger trg_recibo_marca_material after insert or update on public.recibos
  for each row execute function public.fn_recibo_marca_material();

-- horas: BEFORE UPDATE → trg_guarda_correccion (verbatim). El dueño edita
-- libre; el equipo solo con permiso de un uso.
create or replace function public.fn_guarda_correccion() returns trigger
language plpgsql security definer set search_path to 'public','pg_temp' as $$
begin
  if exists (select 1 from perfiles where id = auth.uid() and rol = 'dueno') then
    return new;  -- el dueño edita libre
  end if;
  if old.correccion_estado = 'aprobada' then
    new.correccion_estado := null;  -- permiso de un solo uso
    return new;
  end if;
  if coalesce(new.correccion_estado, '') = 'pedida'
     and new.horas = old.horas and new.fecha = old.fecha
     and coalesce(new.notas, '') = coalesce(old.notas, '')
     and coalesce(new.fase, '') = coalesce(old.fase, '')
     and coalesce(new.proyecto_id, '') = coalesce(old.proyecto_id, '') then
    return new;
  end if;
  raise exception 'Pídele permiso a Edgar para corregir este reporte (toca ✎ y confirma)';
end $$;

drop trigger if exists trg_guarda_correccion on public.horas;
create trigger trg_guarda_correccion before update on public.horas
  for each row execute function public.fn_guarda_correccion();

-- fn_cartero: STUB. En producción manda el aviso al teléfono por
-- net.http_post con un secreto que aquí no existe.
create or replace function public.fn_cartero(cuerpo jsonb) returns void
language plpgsql security definer set search_path to 'public','pg_temp' as $$
begin
  perform 1;
end $$;

-- Avisos de horas (AFTER): en producción arman un mensaje y llaman a
-- fn_cartero. Sus cuerpos no se leyeron; aquí llaman al stub con lo mínimo
-- para que el camino (trigger → fn_cartero → net) exista y no falle.
create or replace function public.fn_avisar_horas() returns trigger
language plpgsql security definer set search_path to 'public','pg_temp' as $$
begin
  perform fn_cartero(jsonb_build_object('tipo', 'horas', 'id', new.id));
  return new;
end $$;

create or replace function public.fn_avisa_correccion() returns trigger
language plpgsql security definer set search_path to 'public','pg_temp' as $$
begin
  if new.correccion_estado is distinct from old.correccion_estado then
    perform fn_cartero(jsonb_build_object('tipo', 'correccion', 'id', new.id));
  end if;
  return new;
end $$;

-- Recordatorio de Notice to Owner: en producción puede insertar en
-- pendientes. No toca nada contable: aquí es un no-op.
create or replace function public.fn_nto_al_apuntar_horas() returns trigger
language plpgsql security definer set search_path to 'public','pg_temp' as $$
begin
  return new;
end $$;

drop trigger if exists trg_avisar_horas on public.horas;
create trigger trg_avisar_horas after insert on public.horas
  for each row execute function public.fn_avisar_horas();
drop trigger if exists trg_avisa_correccion on public.horas;
create trigger trg_avisa_correccion after update on public.horas
  for each row execute function public.fn_avisa_correccion();
drop trigger if exists trg_nto_horas on public.horas;
create trigger trg_nto_horas after insert on public.horas
  for each row execute function public.fn_nto_al_apuntar_horas();

-- =====================================================================
-- RLS: activo en todas, y las policies tal cual están en producción.
-- Donde la policy real no se leyó, va marcada SUPUESTA.
-- =====================================================================
alter table public.perfiles          enable row level security;
alter table public.proyectos         enable row level security;
alter table public.facturas          enable row level security;
alter table public.recibos           enable row level security;
alter table public.horas             enable row level security;
alter table public.materiales        enable row level security;
alter table public.trabajos_externos enable row level security;
alter table public.externos_equipo   enable row level security;
alter table public.costos_equipo     enable row level security;
alter table public.hitos             enable row level security;
alter table public.finanzas_proyecto enable row level security;
alter table public.alcances          enable row level security;
alter table public.codigos_partida   enable row level security;
alter table public.contratistas      enable row level security;
alter table public.asistente_uso     enable row level security;
alter table public.asistente_ajustes enable row level security;
alter table public.escenarios        enable row level security;
alter table public.estimados         enable row level security;
alter table public.catalogo_items    enable row level security;
alter table public.pendientes        enable row level security;
alter table public.gastos_generales  enable row level security;

-- Solo el dueño (reales, "to authenticated").
drop policy if exists "facturas solo dueno" on public.facturas;
create policy "facturas solo dueno" on public.facturas for all to authenticated
  using (es_dueno()) with check (es_dueno());
drop policy if exists "finanzas solo dueno" on public.finanzas_proyecto;
create policy "finanzas solo dueno" on public.finanzas_proyecto for all to authenticated
  using (es_dueno()) with check (es_dueno());
drop policy if exists "hitos solo dueno" on public.hitos;
create policy "hitos solo dueno" on public.hitos for all to authenticated
  using (es_dueno()) with check (es_dueno());
drop policy if exists "alcances solo dueno" on public.alcances;
create policy "alcances solo dueno" on public.alcances for all to authenticated
  using (es_dueno()) with check (es_dueno());
drop policy if exists "costos solo dueno" on public.costos_equipo;
create policy "costos solo dueno" on public.costos_equipo for all to authenticated
  using (es_dueno()) with check (es_dueno());
drop policy if exists "ayudantes solo dueno" on public.externos_equipo;
create policy "ayudantes solo dueno" on public.externos_equipo for all to authenticated
  using (es_dueno()) with check (es_dueno());
drop policy if exists "externos solo dueno" on public.trabajos_externos;
create policy "externos solo dueno" on public.trabajos_externos for all to authenticated
  using (es_dueno()) with check (es_dueno());

-- Solo el dueño (SUPUESTAS: ESQUEMA-REAL dice "dueño todo, equipo nada" pero
-- no se copió el texto de la policy).
drop policy if exists "contratistas solo dueno" on public.contratistas;
create policy "contratistas solo dueno" on public.contratistas for all to authenticated
  using (es_dueno()) with check (es_dueno());
drop policy if exists "gastos generales solo dueno" on public.gastos_generales;
create policy "gastos generales solo dueno" on public.gastos_generales for all to authenticated
  using (es_dueno()) with check (es_dueno());
drop policy if exists "catalogo solo dueno" on public.catalogo_items;
create policy "catalogo solo dueno" on public.catalogo_items for all to authenticated
  using (es_dueno()) with check (es_dueno());
drop policy if exists "escenarios solo dueno" on public.escenarios;
create policy "escenarios solo dueno" on public.escenarios for all to authenticated
  using (es_dueno()) with check (es_dueno());
drop policy if exists "estimados solo dueno" on public.estimados;
create policy "estimados solo dueno" on public.estimados for all to authenticated
  using (es_dueno()) with check (es_dueno());
drop policy if exists "ajustes asistente solo dueno" on public.asistente_ajustes;
create policy "ajustes asistente solo dueno" on public.asistente_ajustes for all to authenticated
  using (es_dueno()) with check (es_dueno());

-- proyectos (reales)
drop policy if exists "editar proyectos" on public.proyectos;
create policy "editar proyectos" on public.proyectos for all using (es_dueno()) with check (es_dueno());
drop policy if exists "leer proyectos" on public.proyectos;
create policy "leer proyectos" on public.proyectos for select using (es_dueno());

-- codigos_partida (reales): el dueño maneja, el equipo lee.
drop policy if exists "dueno maneja codigos" on public.codigos_partida;
create policy "dueno maneja codigos" on public.codigos_partida for all using (es_dueno()) with check (es_dueno());
drop policy if exists "equipo lee codigos" on public.codigos_partida;
create policy "equipo lee codigos" on public.codigos_partida for select using (true);

-- perfiles (reales)
drop policy if exists "dueno agrega perfiles" on public.perfiles;
create policy "dueno agrega perfiles" on public.perfiles for insert with check (es_dueno());
drop policy if exists "dueno edita perfiles" on public.perfiles;
create policy "dueno edita perfiles" on public.perfiles for update using (es_dueno()) with check (es_dueno());
drop policy if exists "leer perfiles" on public.perfiles;
create policy "leer perfiles" on public.perfiles for select using (es_activo());

-- recibos (reales): el equipo solo INSERTA los suyos; lee por recibos_equipo.
drop policy if exists "dueno borra recibos" on public.recibos;
create policy "dueno borra recibos" on public.recibos for delete using (es_dueno());
drop policy if exists "dueno maneja recibos" on public.recibos;
create policy "dueno maneja recibos" on public.recibos for update using (es_dueno()) with check (es_dueno());
drop policy if exists "recibos solo dueno" on public.recibos;
create policy "recibos solo dueno" on public.recibos for select using (es_dueno());
drop policy if exists "subir recibos" on public.recibos;
create policy "subir recibos" on public.recibos for insert with check ((autor_id = auth.uid()) and es_activo());

-- horas (reales)
drop policy if exists "borrar horas" on public.horas;
create policy "borrar horas" on public.horas for delete using (es_dueno());
drop policy if exists "corregir horas" on public.horas;
create policy "corregir horas" on public.horas for update
  using (es_dueno() or ((usuario_id = auth.uid()) and es_activo()))
  with check (es_dueno() or ((usuario_id = auth.uid()) and es_activo()));
drop policy if exists "leer horas" on public.horas;
create policy "leer horas" on public.horas for select using (es_activo());
drop policy if exists "reportar mis horas" on public.horas;
create policy "reportar mis horas" on public.horas for insert with check ((usuario_id = auth.uid()) and es_activo());

-- materiales (reales)
drop policy if exists "agregar materiales" on public.materiales;
create policy "agregar materiales" on public.materiales for insert with check ((autor_id = auth.uid()) and es_activo());
drop policy if exists "dueno borra materiales" on public.materiales;
create policy "dueno borra materiales" on public.materiales for delete using (es_dueno());
drop policy if exists "dueno maneja materiales" on public.materiales;
create policy "dueno maneja materiales" on public.materiales for update using (es_dueno()) with check (es_dueno());
drop policy if exists "materiales solo dueno" on public.materiales;
create policy "materiales solo dueno" on public.materiales for select using (es_dueno());

-- asistente_uso (real): la escribe la edge function con service_role.
drop policy if exists "dueno ve el gasto del asistente" on public.asistente_uso;
create policy "dueno ve el gasto del asistente" on public.asistente_uso for select using (es_dueno());

-- pendientes (SUPUESTAS: la app deja al equipo crear, leer y resolver
-- pendientes; el texto real de las policies no se leyó).
drop policy if exists "leer pendientes" on public.pendientes;
create policy "leer pendientes" on public.pendientes for select using (es_activo());
drop policy if exists "crear pendientes" on public.pendientes;
create policy "crear pendientes" on public.pendientes for insert with check ((autor_id = auth.uid()) and es_activo());
drop policy if exists "resolver pendientes" on public.pendientes;
create policy "resolver pendientes" on public.pendientes for update using (es_activo()) with check (es_activo());
drop policy if exists "dueno borra pendientes" on public.pendientes;
create policy "dueno borra pendientes" on public.pendientes for delete using (es_dueno());

-- =====================================================================
-- Vistas que ya existen
-- =====================================================================

-- recibos_equipo: como en producción, SIN security_invoker (es "security
-- definer" de hecho: corre con los permisos de su dueño, que se salta RLS)
-- y filtra con es_activo(). Así el equipo ve los recibos sin montos.
-- NO es modelo para las vistas del libro: esas llevan security_invoker.
create or replace view public.recibos_equipo as
  select id, proyecto_id, ruta, estado, autor_id, creado
    from recibos
   where es_activo();

-- asistente_costo_mes: en producción es una vista sobre asistente_uso; su
-- texto no se leyó. Esta es una aproximación con las columnas que lee la
-- app (mes, accion, llamadas, centavos), mes de Florida.
create or replace view public.asistente_costo_mes with (security_invoker = true) as
  select to_char((creado at time zone 'America/New_York'), 'YYYY-MM') as mes,
         accion,
         count(*)::int                       as llamadas,
         coalesce(sum(costo_centavos), 0)::int as centavos
    from asistente_uso
   group by 1, 2;
