# Genera la parte de tablas de 01-replica-esquema.sql desde el volcado de
# information_schema.columns de producción (esquema-columnas-23sep.json).
# Uso: python3 generar-tablas.py esquema-columnas-23sep.json > /tmp/tablas.sql
# y pegar el resultado entre la cabecera y las funciones de 01.
import json, sys
d = json.load(open(sys.argv[1]))
T = ('perfiles proyectos facturas recibos horas materiales trabajos_externos externos_equipo '
     'costos_equipo hitos finanzas_proyecto alcances codigos_partida contratistas asistente_uso '
     'asistente_ajustes escenarios estimados catalogo_items pendientes gastos_generales').split()
PK = {'perfiles':'id','proyectos':'id','costos_equipo':'usuario_id','finanzas_proyecto':'proyecto_id',
      'codigos_partida':'codigo','contratistas':'id','asistente_ajustes':'clave','escenarios':'id'}
def tipo(c):
    dt = c['data_type']
    if dt == 'numeric' and c['numeric_precision'] is not None:
        return f"numeric({c['numeric_precision']},{c['numeric_scale']})"
    if dt == 'ARRAY':
        return c['udt_name'][1:] + '[]'
    return {'timestamp with time zone':'timestamptz'}.get(dt, dt)
out = []
for t in T:
    cols = d[t]
    pk = PK.get(t, 'id')
    lineas = []
    for c in cols:
        n = c['column_name']
        s = f"  {n} {tipo(c)}"
        if n == 'id' and c['udt_name'] == 'int8' and c['column_default'] is None:
            s += " generated by default as identity"
        if c['column_default'] is not None:
            s += f" default {c['column_default']}"
        if c['is_nullable'] == 'NO' and n != pk:
            s += " not null"
        if n == pk:
            s += " primary key"
        lineas.append(s)
    out.append(f"create table if not exists public.{t} (\n" + ",\n".join(lineas) + "\n);")
print("\n\n".join(out))
