-- =====================================================================
-- 01-replica-extra.sql — lo que E37 toca y el banco de la contabilidad no
-- replica (o replica como no-op): las funciones COPIADAS TAL CUAL de
-- producción (leídas el 23-sep), sus triggers, las cinco vistas del
-- equipo, y los permisos EXACTOS que tienen hoy en producción.
--
-- fn_cartero lleva un secreto FALSO con el mismo formato que el real,
-- para probar que E37 lo saca y lo guarda en Vault sin enseñarlo.
-- Lo corre editor_sql (el dueño de los objetos, como postgres en Supabase).
-- Solo banco local. No se pega en Supabase.
-- =====================================================================

-- Tablas que faltan -----------------------------------------------------
create table if not exists public.contratista_llaves (
  contratista_id text primary key,
  token          text not null default replace(gen_random_uuid()::text, '-', '')
);
alter table public.contratista_llaves enable row level security;
drop policy if exists "llaves de contratista solo dueno" on public.contratista_llaves;
create policy "llaves de contratista solo dueno" on public.contratista_llaves
  for all to authenticated using (es_dueno()) with check (es_dueno());

create table if not exists public.documentos (
  id          bigint generated by default as identity primary key,
  proyecto_id text,
  clase       text default 'doc',
  titulo      text not null,
  portal      boolean default false
);
alter table public.documentos enable row level security;
drop policy if exists "docs solo dueno" on public.documentos;
create policy "docs solo dueno" on public.documentos
  for all to authenticated using (es_dueno()) with check (es_dueno());
drop policy if exists "rfis los ven todos" on public.documentos;
create policy "rfis los ven todos" on public.documentos
  for select to authenticated using (es_activo() and clase = 'rfi');
insert into public.documentos (proyecto_id, clase, titulo)
  select id, 'doc', 'Contrato de prueba' from public.proyectos order by id limit 1;

-- Funciones, copiadas de producción --------------------------------------
create or replace function public.texto_sin_montos(t text) returns text
language sql immutable set search_path to 'public', 'pg_temp' as $$
  select btrim(regexp_replace(regexp_replace(
    coalesce(t, ''), '\(?\$\s?[0-9][0-9,\.]*\)?', '$•••', 'g'), '\s{2,}', ' ', 'g'));
$$;

create or replace function public.dia_es(f date) returns text
language sql immutable as $$
  select extract(day from f)::text || ' de ' ||
         (array['enero','febrero','marzo','abril','mayo','junio','julio','agosto',
                'septiembre','octubre','noviembre','diciembre'])[extract(month from f)::int] ||
         ' de ' || extract(year from f)::text;
$$;

-- El secreto de aquí es FALSO; el formato es el de producción.
create or replace function public.fn_cartero(cuerpo jsonb) returns void
language plpgsql security definer set search_path to 'public', 'pg_temp' as $$
begin
  perform net.http_post(
    url := 'https://zeogjvwcmstmkwxjvykz.supabase.co/functions/v1/notificar',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-mxp-secreto', 'mxp_deadbeefdeadbeefdeadbeefdeadbeefdeadbeef'),
    body := cuerpo
  );
end $$;

create or replace function public.fn_mandar_urgente(txt text, pid text) returns void
language plpgsql security definer set search_path to 'public', 'pg_temp' as $$
declare
  nom text;
  limpio text;
begin
  select nombre into nom from proyectos where id = pid;
  limpio := regexp_replace(coalesce(txt, ''), '\$\s?[0-9][0-9,.]*', '$•••', 'g');
  perform fn_cartero(jsonb_build_object(
    'titulo', '🔴 URGENTE',
    'cuerpo', limpio || ' — ' || coalesce(nom, 'General')));
end $$;

create or replace function public.fn_urgente_pendiente() returns trigger
language plpgsql security definer set search_path to 'public', 'pg_temp' as $$
begin
  if new.prioridad = 'urgente'
     and (tg_op = 'INSERT' or old.prioridad is distinct from 'urgente')
     and not coalesce(new.resuelto, false) then
    perform fn_mandar_urgente(new.descripcion, new.proyecto_id);
  end if;
  return new;
end $$;

create or replace function public.fn_avisar_horas() returns trigger
language plpgsql security definer set search_path to 'public', 'pg_temp' as $$
begin
  if exists (select 1 from perfiles where id = new.usuario_id and rol <> 'dueno') then
    perform fn_cartero(jsonb_build_object('table', 'horas', 'record', to_jsonb(new)));
  end if;
  return new;
end $$;

create or replace function public.fn_nto_recordatorio(p_proyecto text) returns void
language plpgsql security definer set search_path to 'public', 'pg_temp' as $$
declare
  v_modo   text;
  v_nombre text;
  v_ya     timestamptz;
  v_horas  date;
  v_recibo date;
  v_primer date;
  v_limite date;
  v_hoy    date := (now() at time zone 'America/New_York')::date;
  v_texto  text;
  v_abierto record;
begin
  select p.contratista_modo, p.nombre, p.nto_enviado_el
    into v_modo, v_nombre, v_ya
    from proyectos p where p.id = p_proyecto;
  if v_modo is distinct from 'contrato' or v_ya is not null then return; end if;
  select min(h.fecha) into v_horas  from horas h   where h.proyecto_id = p_proyecto;
  select min(r.fecha) into v_recibo from recibos r where r.proyecto_id = p_proyecto
                                                    and coalesce(r.estado,'') <> 'anulado';
  v_primer := least(coalesce(v_horas, v_recibo, v_hoy), coalesce(v_recibo, v_horas, v_hoy));
  v_limite := v_primer + 40;
  if v_primer + 45 < v_hoy then
    v_texto := 'OJO — el plazo del Notice to Owner de ' || coalesce(v_nombre, p_proyecto) ||
               ' YA SE PASÓ: el primer día de trabajo fue el ' || dia_es(v_primer) ||
               ' y los 45 días vencieron el ' || dia_es(v_primer + 45) ||
               '. Consúltalo antes de mandarlo. Cuando lo mandes, márcalo en la obra.';
    v_limite := v_hoy;
  else
    v_texto := 'Mandar el Notice to Owner de ' || coalesce(v_nombre, p_proyecto) ||
               ' al dueño de la propiedad y al contratista antes del ' || dia_es(v_limite) ||
               '. Te lo pongo cinco días antes a propósito: el plazo de ley se cumple el ' ||
               dia_es(v_primer + 45) || ', 45 días desde el primer día de trabajo (' ||
               dia_es(v_primer) || '). Sin esto se pierde el derecho a gravamen. ' ||
               'Cuando lo mandes, márcalo en la obra y anota cómo.';
    if v_limite < v_hoy then v_limite := v_hoy; end if;
  end if;
  select * into v_abierto from pendientes
   where proyecto_id = p_proyecto
     and (descripcion like 'Mandar el Notice to Owner%' or descripcion like 'OJO — el plazo del Notice to Owner%')
   order by coalesce(resuelto, false), id desc
   limit 1;
  if found then
    if not coalesce(v_abierto.resuelto, false) and v_abierto.fecha > v_limite then
      update pendientes set fecha = v_limite, descripcion = v_texto where id = v_abierto.id;
    end if;
    return;
  end if;
  insert into pendientes (proyecto_id, descripcion, fecha, prioridad, resuelto, autor_id)
  values (p_proyecto, v_texto, v_limite, 'urgente', false,
          coalesce(auth.uid(), '00000000-0000-4000-a000-000000000001'::uuid));
end $$;

create or replace function public.fn_nto_al_apuntar_horas() returns trigger
language plpgsql security definer set search_path to 'public', 'pg_temp' as $$
begin
  if exists (select 1 from proyectos p
              where p.id = new.proyecto_id and p.contratista_modo = 'contrato'
                and p.nto_enviado_el is null) then
    perform fn_nto_recordatorio(new.proyecto_id);
  end if;
  return new;
end $$;

create or replace function public.fn_nto_al_arrancar() returns trigger
language plpgsql security definer set search_path to 'public', 'pg_temp' as $$
begin
  if new.contratista_modo = 'contrato' and new.estado = 'ejecucion' then
    if tg_op = 'INSERT' then
      perform fn_nto_recordatorio(new.id);
    elsif old.estado is distinct from new.estado
       or old.contratista_modo is distinct from new.contratista_modo then
      perform fn_nto_recordatorio(new.id);
    end if;
  end if;
  return new;
end $$;

create or replace function public.fn_nto_al_resolver() returns trigger
language plpgsql security definer set search_path to 'public', 'pg_temp' as $$
begin
  if coalesce(new.resuelto, false) and not coalesce(old.resuelto, false)
     and new.proyecto_id is not null
     and (new.descripcion like 'Mandar el Notice to Owner%'
       or new.descripcion like 'OJO — el plazo del Notice to Owner%') then
    update proyectos set nto_enviado_el = coalesce(nto_enviado_el, now())
     where id = new.proyecto_id;
  end if;
  return new;
end $$;

create or replace function public.fn_llave_contratista_nueva() returns trigger
language plpgsql security definer set search_path to 'public', 'pg_temp' as $$
begin
  insert into contratista_llaves (contratista_id, token)
  values (new.id, replace(gen_random_uuid()::text, '-', ''))
  on conflict (contratista_id) do nothing;
  return new;
end $$;

create or replace function public.fn_estuve() returns void
language sql security definer set search_path to 'public' as $$
  update perfiles set ultima_vista = now() where id = auth.uid();
$$;

-- Las tres sin search_path, tal cual (E37 se lo pone)
create or replace function public.fn_lev_tocado() returns trigger language plpgsql as $$
begin
  new.actualizado := now();
  return new;
end $$;
create or replace function public.planos_touch() returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end $$;
create or replace function public.fn_diario_punto() returns trigger
language plpgsql security definer as $$
begin
  if new.hecho and not old.hecho and new.proyecto_id is not null then
    insert into diario (proyecto_id, texto) values (new.proyecto_id, '✓ ' || coalesce(new.texto_en, new.texto));
  end if;
  return new;
end $$;
-- fn_factura_cobrada: en producción tampoco tiene search_path
create or replace function public.fn_factura_cobrada() returns trigger language plpgsql as $$
begin
  if new.pagada = true and (old.pagada is distinct from true) and coalesce(new.cobrado, 0) < new.monto then
    new.cobrado := new.monto;
  end if;
  if new.cobrado is null then new.cobrado := case when new.pagada then new.monto else 0 end; end if;
  return new;
end $$;
alter function public.fn_factura_cobrada() reset search_path;

-- Triggers, como en producción ------------------------------------------
drop trigger if exists trg_avisar_horas on public.horas;
create trigger trg_avisar_horas after insert on public.horas
  for each row execute function public.fn_avisar_horas();
drop trigger if exists trg_nto_horas on public.horas;
create trigger trg_nto_horas after insert on public.horas
  for each row execute function public.fn_nto_al_apuntar_horas();
drop trigger if exists trg_nto_proyecto on public.proyectos;
create trigger trg_nto_proyecto after insert or update on public.proyectos
  for each row execute function public.fn_nto_al_arrancar();
drop trigger if exists trg_urgente_pendiente on public.pendientes;
create trigger trg_urgente_pendiente after insert or update of prioridad on public.pendientes
  for each row execute function public.fn_urgente_pendiente();
drop trigger if exists trg_nto_resuelto on public.pendientes;
create trigger trg_nto_resuelto after update on public.pendientes
  for each row execute function public.fn_nto_al_resolver();
drop trigger if exists trg_llave_contratista on public.contratistas;
create trigger trg_llave_contratista after insert on public.contratistas
  for each row execute function public.fn_llave_contratista_nueva();

-- Las cinco vistas del equipo, copiadas de producción (SECURITY DEFINER:
-- sin security_invoker) ---------------------------------------------------
create or replace view public.proyectos_equipo as
  select id, nombre, direccion, cliente, via, tipo, work_subtype, estado, fase, origen,
         horas_estimadas, horas_reales_base, actualizado, portal_completo, portal_dinero,
         texto_sin_montos(estado_detalle) as estado_detalle,
         texto_sin_montos(proxima_accion) as proxima_accion,
         texto_sin_montos(ref) as ref
    from proyectos where es_activo();
create or replace view public.materiales_equipo as
  select id, proyecto_id, descripcion, cantidad, estado, origen_pendiente, autor_id, creado
    from materiales where es_activo();
create or replace view public.alcances_equipo as
  select id, proyecto_id, tipo, titulo, ref, estado, orden from alcances where es_activo();
create or replace view public.documentos_equipo as
  select id, proyecto_id, titulo, clase from documentos where es_activo();
-- recibos_equipo ya la crea el banco; se rehace igual que en producción.
create or replace view public.recibos_equipo as
  select id, proyecto_id, ruta, estado, autor_id, creado from recibos where es_activo();
drop view if exists public.asistente_costo_mes;
create view public.asistente_costo_mes with (security_invoker = true) as
  select to_char((creado at time zone 'America/New_York'), 'YYYY-MM') as mes,
         coalesce(accion, 'asistente') as accion, count(*) as llamadas,
         coalesce(sum(costo_centavos), 0) as centavos
    from asistente_uso group by 1, 2;

-- Permisos EXACTOS de producción (23-sep) ----------------------------------
-- Vistas: como en producción, anon y authenticated lo tienen TODO.
do $$
declare v text;
begin
  foreach v in array array['proyectos_equipo','recibos_equipo','materiales_equipo',
                           'alcances_equipo','documentos_equipo','asistente_costo_mes'] loop
    execute format('grant all on public.%I to anon, authenticated, service_role', v);
  end loop;
end $$;

-- Funciones: tres grupos, tal cual los devuelve pg_proc.proacl.
do $$
declare f text;
begin
  -- Con PUBLIC (=X/postgres): las ocho que el asesor marca.
  foreach f in array array['public.fn_llave_contratista_nueva()', 'public.fn_nto_al_apuntar_horas()',
      'public.fn_nto_al_arrancar()', 'public.fn_nto_al_resolver()', 'public.fn_nto_recordatorio(text)',
      'public.dia_es(date)', 'public.fn_factura_cobrada()', 'public.fn_lev_tocado()'] loop
    execute format('revoke all on function %s from public, anon, authenticated, service_role', f);
    execute format('grant execute on function %s to public, authenticated, service_role', f);
  end loop;
  -- authenticated + service_role.
  foreach f in array array['public.es_dueno()', 'public.es_activo()', 'public.fn_avisar_horas()',
      'public.fn_avisa_correccion()', 'public.fn_urgente_pendiente()', 'public.fn_estuve()',
      'public.fn_diario_punto()', 'public.planos_touch()', 'public.texto_sin_montos(text)',
      'public.fn_guarda_correccion()', 'public.fn_recibo_marca_material()'] loop
    if to_regprocedure(f) is not null then
      execute format('revoke all on function %s from public, anon, authenticated, service_role', f);
      execute format('grant execute on function %s to authenticated, service_role', f);
    end if;
  end loop;
  -- Solo el servidor.
  foreach f in array array['public.fn_cartero(jsonb)', 'public.fn_mandar_urgente(text,text)'] loop
    execute format('revoke all on function %s from public, anon, authenticated, service_role', f);
    execute format('grant execute on function %s to service_role', f);
  end loop;
end $$;
